name: Create Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # Trigger on version tags
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build extension
        run: npm run gulp -- build
        
      - name: Create zip file
        run: cd dist && zip -r ../extension.zip *
        
      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(node -p "require('./app/manifest.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: extension.zip
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          body: |
            ## Changes in this release
            
            This release includes the migration to Chrome Extension Manifest V3, which is required for all Chrome extensions as of 2024.
            
            ### Key Changes
            - Updated manifest structure to V3 format
            - Converted background script to service worker
            - Updated permissions model to use host_permissions
            - Removed deprecated APIs and features
            - Added new build process
            - Updated documentation
            
            ### Installation
            1. Download the extension.zip file
            2. Unzip the file
            3. Open Chrome and go to chrome://extensions/
            4. Enable "Developer mode" in the top right
            5. Click "Load unpacked" and select the unzipped extension folder
            
            ### Note
            This is a fork of the original [StoryPoint for Asana](https://chrome.google.com/webstore/detail/storypoint-for-asana/ipkcinfcdhhcmibffhlklololceffgnc) extension, updated to support Manifest V3. 